### ISSUE TITLE
Installing AlphaSpace

### ISSUE THREAD

**Issue by mscockatiel** [RedesignScience/AlphaSpace2#18]
Hello,

I am an undergraduate student trying to use AlphaSpace2 in my research lab. I have been using the terminal application on macOS Catalina. The command "pip install alphaspace2" gives the attached error. 

<img width="716" alt="Screen Shot 2020-10-02 at 12 45 02 AM" src="https://user-images.githubusercontent.com/71343207/94888905-832f3e80-0448-11eb-9236-caabb7f925ba.png">

I was able to successfully download the program using the git clone command and pip install -e ./ command onto my desktop. However, I believe that python does not recognize AlphaSpace2 as a module/package, but rather, a program. I tried to run a script using the tutorials you provided, but then the following error occurs. The system can properly import other packages such as numpy and mdtraj as well as alphaspace2.py from the bin. However, it gives an error when trying to import subsections of alphaspace2. I have also included the output of pip list. I am not sure what the issue is. Perhaps it has something to do with my paths? 

<img width="675" alt="Screen Shot 2020-10-02 at 2 40 48 AM" src="https://user-images.githubusercontent.com/71343207/94895097-af52bb80-0458-11eb-8203-5693830592ac.png">

Please advise on how to carry forward. I am a novice and not sure how to properly install your program as a module of python. 

Thank you and take care.

**Comment by lenhsherr** [comment]
Hi,

Thanks for letting me know, I can reproduce the pip installation error on my end, probably because the version was not updated after some bug fixes. I will update the Pypi server and let you know.

However I cannot reproduce the error on my end for local installation, which version of python are you using? And are you using the mac stock python or anaconda and other package manager?

**Comment by mscockatiel** [comment]
Thank you for getting back to me so quickly! I am using python 3.8.5 on my system and am installing most things using pip as a package manager. My system's pip currently does not label alphaspace2 as a package, so I'm not sure if that's the problem.

**Comment by lenhsherr** [comment]
I would suggest using a conda environment for this. I’m reuploading the package to pip so that will be resolved. Can you test the conda pip installation through local clone and let me know?

**Comment by mscockatiel** [comment]
I installed anaconda and I tried running "conda install alphaspace2", which gave this error. Not sure if that's what you were asking. I also retried "pip install alphaspace2" and that gives the same error. 
<img width="679" alt="Screen Shot 2020-10-02 at 9 01 44 PM" src="https://user-images.githubusercontent.com/71343207/94979722-7bc46f80-04f2-11eb-9c9c-eacffb449973.png">

**Comment by lenhsherr** [comment]
No, this is not uploaded to Conda so you can't use conda to install, you need to install with the pip included within the conda package. You can make sure you are using the conda pip with `which pip`

Then use the `pip install -e ./` to install the package from the root folder of AlphaSpace2

**Comment by mscockatiel** [comment]
Thank you for your help, AlphaSpace2 now works on my system :)
